api_version = "2025-04"

[[extensions]]
uid = "c992d8a7-d734-ca5b-238e-282fcc9d779353d727b0"
type = "theme"
name = "Wishlist Button"
handle = "wishlist-button"

# UID is injected by `shopify app dev` / `shopify app deploy` if omitted.
