api_version = "2025-10"

[[extensions]]
name = "My Wishlist"
handle = "customer-account-wishlist"
uid = "2842f224-d987-cfea-47c3-182398c28d103c711e42"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/FullPageExtension.jsx"
target = "customer-account.page.render"

[extensions.capabilities]
api_access = true
network_access = true
