name = "variant-filter-app"
main = "server.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./build/client"

# Secrets (set via `wrangler secret put <KEY>`):
#   SHOPIFY_API_KEY
#   SHOPIFY_API_SECRET
#   SHOPIFY_APP_URL
#   APP_URL = https://variant-filter-app.rocky-horizon-development.workers.dev

[[kv_namespaces]]
# Create with: wrangler kv namespace create SESSION_KV
binding = "SESSION_KV"
id = "a6a516d2496344e1b1de17dc819abc05"

[env.preview]
[[env.preview.kv_namespaces]]
# Create with: wrangler kv namespace create SESSION_KV --preview
binding = "SESSION_KV"
id = "d6fe97a3576a4efcb96e17797639a7b8"


